Feature.create([
  {:name => 'Shelter of the Faithful',
   :description => 'As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle. You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there, This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home, While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.',
   :table => {},
   :race_id => '',
   :class_id => '',
  },
  {:name => 'Frenzy',
   :description => 'Starting when you choose this path at level 3, you can go into a frenzy when you rage. If you do so, for the duration of your rage you can make a single melee weapon attack as a bonus action on each of your turns after this one. When your rage ends, you suffer one level of exhaustion.',
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Mindless Rage',
   :description => "Beginning at the 6th level, you can't be charmed or frightened while raging. If you are charm ed or frightened when you enter your rage, the effect is suspended for the duration of the rage.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Intimidating Presence',
   :description => "Beginning at the 10th level, you can use your action to frighten someone with your menacing presence. When you do so, choose one creature that you can see within 30 feet of you. If the creature can see or hear you, it must succeed on a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Charisma modifier) or be frightened of you until the end of your next turn. On subsequent turns, you can use your action to extend the duration of this effect on the frightened creature until the end of your next turn. This effect ends if the creature ends its turn out of line of sight or more than 60 feet away from you. If the creature succeeds on its saving throw, you can't use this feature on that creature again for 24 hours.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Retaliation',
   :description => 'Starting at the 14th level, when you take damage from a creature that is within 5 feet of you, you can use your reaction to make a melee weapon attack against that creature.',
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Rage',
   :description => "In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren't wearing heavy armor:<ul><li>You have advantage on Strength checks and Strength saving throws.</li><li>When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, as shown in the Rage Damage column of the Barbarian table.</li><li>You have resistance to bludgeoning, piercing, and slashing damage.</li></ul>If you are able to cast spells, you can’t cast them or concentrate on them while raging. Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven’t attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action. Once you have raged the number of times shown for your barbarian level in the Rages column of the Barbarian table, you must finish a long rest before you can rage again.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Unarmored Defense',
   :description => "While you are not wearing any armor, your Arm or Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => "False Identity",
   :description => "You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Criminal Contact",
   :description => "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how lo gel messages lo and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "By Popular Demand",
   :description => "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Rustic Hospitality",
   :description => "Since you come from the ranks of the common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among other commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Guild Membership",
   :description => "As an established and respected member of a guild, you can rely on certain benefits that membership provides. Your fellow guild members will provide you with lodging and food if necessary, and pay for your funeral if needed. In some cities and towns, a guildhall offers a central place to meet other members of your profession, which can be a good place to meet potential patrons, allies, or hirelings. Guilds often wield tremendous political power. If you are accused of a crime, your guild will support you if a good case can be made for your innocence or the crime is justifiable. You can also gain access to powerful political figures through the guild, if you are a member in good standing. Such connections might require the donation of money or magic items to the guild's coffers. You must pay dues of 5 GP per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Discovery",
   :description => "The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery. The exact nature of this revelation depends on the nature of your seclusion. It might be a great truth about the cosmos, the deities, the powerful beings of the outer planes, or the forces of nature. It could be a site that no one else has ever seen. You might have uncovered a fact that has long been forgotten, or unearthed some relic of the past that could rewrite history. It might be information that would be damaging to the people who or consigned you to exile, and hence the reason for your return to society. Work with your DM to determine the details of your discovery and its impact on the campaign.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Position of Privilege",
   :description => "Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Wanderer",
   :description => "You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Researcher",
   :description => "When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature, Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found. Unearthing the deepest secrets of the multi-verse can require an adventure or even a whole campaign.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Ship's Passage",
   :description => "When you need to, you can secure free passage on a sailing ship for yourself and your adventuring companions. You might sail on the ship you served on, or another ship you have good relations with (perhaps one captained by a former crewmate). Because you're calling in a favor, you can't be certain of a schedule or route that will meet your every need. Your Dungeon Master will determine how long it takes to get where you need to go. In return for your free passage, you and your companions are expected to assist the crew during the voyage.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "Military Rank",
   :description => "You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influence over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => "City Secrets",
   :description => "You know the secret patterns and flow to cities and can find passages through the urban sprawl that others would miss. When you are not in combat, you (and companions you lead) can travel between any two locations in the city twice as fast as your speed would normally allow.",
   :table => {},
   :race_id => '',
   :class_id => ''
  },
  {:name => 'Bad Reputation',
   :description => "No matter where you go, people are afraid of you due to your reputation. When you are in a civilized settlement, you can gel away with minor criminal offenses, such as refusing to pay for food at a tavern or breaking down doors at a local shop, since most people will not report your activity to the authorities.",
   :table => {},
   :race_id => '',
   :class_id => ''
  }
])
