BackgroundExtra.create([
  {:name => "Suggested Characteristics",
   :description => "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.",
   :values => {},
   :background_id => 1
  },
  {:name => "Suggested Characteristics",
   :description => "Charlatans are colorful characters who conceal their true selves behind the masks they construct. They reflect what people want to see, what they want to believe, and how they see the world. But their true selves are sometimes plagued by an uneasy conscience, an old enemy, or deep-seated trust issues.",
   :values => {},
   :background_id => 2,
  },
  {:name => "Favorite Schemes",
   :description => "Every charlatan has an angle he or she uses in preference to other schemes. Choose a favorite scam or roll on the table below.",
   :values => {
     headers: ['d6', 'Scam'],
     rows: [
       ['1', "I cheat at games of chance"],
       ['2', "I shave coins or forge documents"],
       ['3', "I insinuate myself into people's lives to prey on their weakness and secure their fortunes"],
       ['4', "I put on new identities like clothes"],
       ['5', "I run sleight-of-hand cons on street corners"],
       ['6', "I convince people that worthless junk is worth their hard-earned money"]
     ]
   },
   :background_id => 2,
  },
  {:name => "Suggested Characteristics",
   :description => "You have a reliable and trustworthy contact who acts as your liaison lo a network of other criminals. You know how lo gel messages lo and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.",
   :values => {},
   :background_id => 3,
  },
  {:name => "Criminal Specialty",
   :description => "There are many kinds of criminals, and within a thieves' guild or similar criminal organization, individual members have particular specialties. Even criminals who operate outside of such organizations have strong preferences for certain kinds of crimes over others. Choose the role you played in your criminal life, or roll on the table below.",
   :values => {
     headers: ['d8', 'Specialty'],
     rows: [
       ['1', "Blackmailer"],
       ['2', "Burglar"],
       ['3', "Enforcer"],
       ['4', "Fence"],
       ['5', "Highway Robber"],
       ['6', "Hired Killer"],
       ['7', "Pickpocket"],
       ['8', "Smuggler"]
     ]
   },
   :background_id => 3,
  },
  {:name => "Suggested Characteristics",
   :description => "Successful entertainers have to be able to capture and hold an audience's attention, so they tend to have flamboyant or forceful personalities. They're inclined toward the romantic and often cling to high-minded ideals about the practice of art and the appreciation of beauty.",
   :values => {},
   :background_id => 4,
  },
  {:name => "Entertainer Routines",
   :description => "A good entertainer is versatile, spicing up every performance with a variety of different routines. Choose one to three routines or roll on the table below to define your expertise as an entertainer.",
   :values => {
     headers: ['d10', 'Entertainer Routine'],
     rows: [
       ['1', "Actor"],
       ['2', "Dancer"],
       ['3', "Fire-eater"],
       ['4', "Jester"],
       ['5', "Juggler"],
       ['6', "Instrumentalist"],
       ['7', "Poet"],
       ['8', "Singer"],
       ['9', "Storyteller"],
       ['10', "Tumbler"],
     ]
   },
   :background_id => 4,
  },
  {:name => "Suggested Characteristics",
   :description => "A folk hero is one of the common people, for better or for worse. Most folk heroes look on their humble origins as a virtue, not a shortcoming, and their home communities remain very important to them.",
   :values => {},
   :background_id => 5,
  },
  {:name => "Defining Event",
   :description => "You previously pursued a simple profession among the peasantry, perhaps as a farmer, miner, servant, shepherd, woodcutter, or gravedigger. But something happened that set you on a different path and marked you for greater things. Choose or randomly determine a defining event that marked you as a hero of the people.",
   :values => {
     headers: ['d10', 'Defining Event'],
     rows: [
       ['1', "I stood up to a tyrant's agents"],
       ['2', "I saved people during a natural disaster"],
       ['3', "I stood alone against a terrible monster"],
       ['4', "I stole from a corrupt merchant to help the poor"],
       ['5', "I led a militia to fight off an invading army"],
       ['6', "I broke into a tyrant's castle and stole weapons to arm the people"],
       ['7', "I trained the peasantry to use farm implements as weapons against a tyrant's soldiers"],
       ['8', "A lord rescinded an unpopular decree after I led a symbolic act of protest against it"],
       ['9', "A celestial, fey, or similar creature gave me a blessing or revealed my secret origin"],
       ['10', "Recruited into a lord's army, I rose to leadership and was commended for my heroism"]
     ]
   },
   :background_id => 5,
  },
  {:name => "Suggested Characteristics",
   :description => "Some hermits are well suited to a life of seclusion, whereas others chafe against it and long for company. Whether they embrace solitude or long to escape it, the solitary life shapes their attitudes and ideals. A few are driven slightly mad by their years apart from society.",
   :values => {},
   :background_id => 6,
  },
  {:name => "Life of Seclusion",
   :description => "What was the reason for your isolation, and what changed to allow you to end your solitude? You can work with your DM to determine the exact nature of your seclusion, or you can choose or roll on the table below to determine the reason behind your seclusion.",
   :values => {
     headers: ['d8', 'Life of Seclusion'],
     rows: [
       ['1', "I was searching for spiritual enlightenment"],
       ['2', "I was partaking of communal living in accordance with the dictates of a religious order"],
       ['3', "I was exiled for a crime I didn't commit"],
       ['4', "I retreated from society after a life-altering event"],
       ['5', "I needed a quiet place to work on my art, literature, music, or manifesto"],
       ['6', "I needed to commune with nature, far from civilization"],
       ['7', "I was the caretaker of an ancient ruin or relic"],
       ['8', "I was a pilgrim in search of a person, place, or relic of spiritual significance"]
     ]
   },
   :background_id => 6,
  },
  {:name => "Suggested Characteristics",
   :description => "Guild artisans are among the most ordinary people in the world-until they set down their tools and take up an adventuring career. They understand the value of hard work and the importance of community, but they're vulnerable to sins of greed and covetousness.",
   :values => {},
   :background_id => 7,
  },
  {:name => "Guild Business",
   :description => "Guilds are generally found in cities large enough to support several artisans practicing the same trade. However, your guild might instead be a loose network of artisans who each work in a different village within a larger realm. Work with your DM to determine the nature of your guild. You can select your guild business from the Guild Business table or roll randomly.",
   :values => {
     headers: ['d20', 'Guild Business'],
     rows: [
       ['1', "Alchemists and apothecaries"],
       ['2', "Armorers, locksmiths, and finesmiths"],
       ['3', "Brewers, distillers, and vintners"],
       ['4', "Calligraphers, scribes, and scriveners"],
       ['5', "Carpenters, roofers, and plasterers"],
       ['6', "Cartographers, surveyors, and chart-makers"],
       ['7', "Cobblers and shoemakers"],
       ['8', "Cooks and bakers"],
       ['9', "Glassblowers and glaziers"],
       ['10', "Jewelers and gemcutters"],
       ['11', "Leatherworkers, skinners, and tanners"],
       ['12', "Masons and stonecutters"],
       ['13', "Painters, limners, and sign-makers"],
       ['14', "Potters and tile-makers"],
       ['15', "Shipwrights and sailmakers"],
       ['16', "Smiths and metal-forgers"],
       ['17', "Tinkers, pewterers, and casters"],
       ['18', "Wagon-makers and wheelwrights"],
       ['19', "Weavers and dyers"],
       ['20', "Woodcarvers, coopers, and bowyers"]
     ]
   },
   :background_id => 7,
  },
  {:name => "Suggested Characteristics",
   :description => "Nobles are born and raised to a very different lifestyle than most people ever experience, and their personalities reflect that upbringing. A noble title comes with a plethora of bonds-responsibilities to family, to other nobles (including the sovereign), to the people entrusted to the family's care, or even to the title itself. But this responsibility is often a good way to undermine a noble.",
   :values => {},
   :background_id => 8,
  },
  {:name => "Suggested Characteristics",
   :description => "Often considered rude and uncouth among civilized folk, outlanders have little respect for the niceties of life in the cities. The ties of tribe, clan, family, and the natural world of which they are a part are the most important bonds lo most outlanders.",
   :values => {},
   :background_id => 9,
  },
  {:name => "Origin",
   :description => "You've been to strange places and seen things that others cannot begin to fathom. Consider some of the distant lands you have visited, and how they impacted you. You can roll on the following table lo determine your occupation during your time in the wild, or choose one that best fits your character.",
   :values => {
     headers: ['d10', 'Origin'],
     rows: [
       ['1', "Forester"],
       ['2', "Trapper"],
       ['3', "Homesteader"],
       ['4', "Guide"],
       ['5', "Exile or outcast"],
       ['6', "Bounty hunter"],
       ['7', "Pilgrim"],
       ['8', "Tribal nomad"],
       ['9', "Hunter-gatherer"],
       ['10', "Tribal marauder"]
     ]
   },
   :background_id => 9,
  },
  {:name => "Suggested Characteristics",
   :description => "Sages are defined by their extensive studies, and their characteristics reflect this life of study. Devoted to scholarly pursuits, a sage values knowledge highly- sometimes in its own right, sometimes as a means toward other ideals.",
   :values => {},
   :background_id => 10,
  },
  {:name => "Specialty",
   :description => "To determine the nature of your scholarly training, roll a d8 or choose from the options in the table below.",
   :values => {
     headers: ['d8', 'Specialty'],
     rows: [
       ['1', "Alchemist"],
       ['2', "Astronomer"],
       ['3', "Discredited academic"],
       ['4', "Librarian"],
       ['5', "Professor"],
       ['6', "Researcher"],
       ['6', "Wizard's apprentice"],
       ['8', "Scribe"]
     ]
   },
   :background_id => 10,
  },
  {:name => "Suggested Characteristics",
   :description => "Sailors can be a rough lot, but the responsibilities of life on a ship make them generally reliable as well. Life aboard a ship shapes their outlook and forms their most important attachments.",
   :values => {},
   :background_id => 11,
  },
  {:name => "Suggested Characteristics",
   :description => "The horrors of war combined with the rigid discipline of military service leave their mark on all soldiers, shaping their ideals, creating strong bonds, and often leaving them scarred and vulnerable to fear, shame, and hatred.",
   :values => {},
   :background_id => 12,
  },
  {:name => "Specialty",
   :description => "During your time as a soldier, you had a specific role to play in your unit or army. Roll a d8 or choose from the options in the table below to determine your role:",
   :values => {
     headers: ['d8', 'Specialty'],
     rows: [
       ['1', "Officer"],
       ['2', "Scout"],
       ['3', "Infantry"],
       ['4', "Cavalry"],
       ['5', "Healer"],
       ['6', "Quartermaster"],
       ['7', "Standard bearer"],
       ['8', "Support staff"]
     ]
   },
   :background_id => 12,
  },
  {:name => "Suggested Characteristics",
   :description => "Urchins are shaped by lives of desperate poverty, for good and for ill. They tend to be driven either by a commitment to the people with whom they shared life 00 the street or by a burning desire to find a better life- and maybe get some payback on all the rich people who treated them badly.",
   :values => {},
   :background_id => 13,
  }
])
