CharClass.create([
  {:name => 'Barbarian',
   :description => 'A fierce warrior of primitive background who can enter a battle rage',
   :image => 'barbarian.png',
   :primary_ability => 'Str',
   :bio => "A tall human tribesman strides through a blizzard, draped in fur and hefting his axe. He laughs as he charges toward the frost giant who dared poach his people's elk herd. A half-orc snarls at the latest challenger to her authority over their savage tribe, ready to break his neck with her bare hands as she did to the last six rivals. Frothing at the mouth, a dwarf slams his helmet into the face of his drow foe, then turns to drive his armored elbow into the gut of another. These barbarians, different as they might be, are defined by their rage: unbridled, unquenchable, and unthinking fury. More than a mere emotion, their anger is the ferocity of a cornered predator, the unrelenting",
   :saving_throws => ['Str', 'Con'],
   :hit_dice => '1d12',
   :hp_at_first_level => 12,
   :hp_at_first_level_attribute => 'Con',
   :hp_at_higher_levels => '1d12',
   :hp_at_higher_levels_min => 7,
   :hp_at_higher_levels_attribute => 'Con',
   :starting_equipment => {items: [
     {quantity: 1, choices: ['Greataxe', 'Any Martial Weapon']},
     {quantity: [2,1], choices: ['Handaxe', 'Any Simple Weapon']},
     {quantity: 1, choices: ["Explorer's Pack"]},
     {quantity: 4, choices: ["Javelin"]},
   ]},
   :armor_prof => ['Light Armor', 'Medium Armor', 'Shield'],
   :weapon_prof => ['Simple Weapon', 'Martial Weapon'],
   :skill_prof => 2,
   :tool_prof => [],
   :skill_prof_choices => [2, 4, 8, 11, 12, 18],
   :fund_modifier => 10,
   :fund_roll => '2d4'
  },
  {:name => 'Bard',
   :description => "An inspiring magician whose power echoes the music of creation.",
   :image => 'bard.jpg',
   :primary_ability => 'Cha',
   :bio => "Humming as she traces her fingers over an ancient monument in a long-forgotten ruin, a half-elf in rugged leathers finds knowledge springing into her mind, conjured forth by the magic of her song—knowledge of the people who constructed the monument and the mythic saga it depicts. A stern human warrior bangs his sword rhythmically against his scale mail, setting the tempo for his war chant and exhorting his companions to bravery and heroism. The magic of his song fortifies and emboldens them. Laughing as she tunes her cittern, a gnome weaves her subtle magic over the assem bled nobles, ensuring that her companions’ words will be well received. Whether scholar, skald, or scoundrel, a bard weaves magic through words and music to inspire allies, demoralize foes, manipulate minds, create illusions, and even heal wounds.",
   :saving_throws => ['Dex', 'Cha'],
   :hit_dice => '1d8',
   :hp_at_first_level => 7,
   :hp_at_first_level_attribute => 'Con',
   :hp_at_higher_levels => '1d8',
   :hp_at_higher_levels_min => 5,
   :hp_at_higher_levels_attribute => 'Con',
   :starting_equipment => {items: [
     {quantity: 1, choices: ['Rapier', 'Longsword', 'Any Simple Weapon']},
     {quantity: 1, choices: ["Diplomat's Pack", "Entertainer's Pack"]},
     {quantity: 1, choices: ["Lute", "Any Musical Instrument"]},
     {quantity: 1, choices: ['Leather Armor']},
     {quantity: 1, choices: ['Dagger']}
   ]},
   :armor_prof => ['Light Armor'],
   :weapon_prof => ['Simple Weapon', 'Hand Crossbow', 'Longsword', 'Rapier', 'Shortsword'],
   :skill_prof => 3,
   :tool_prof => ['Musical Instrument', 'Musical Instrument', 'Musical Instrument'],
   :skill_prof_choices => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],
   :fund_modifier => 10,
   :fund_roll => '5d4'
  },
  {:name => 'Cleric',
   :description => "A priestly champion who wields divine magic in service of a higher power",
   :image => 'cleric.jpg',
   :primary_ability => 'Wis',
   :bio => "Arms and eyes upraised toward the sun and a prayer on his lips, an elf begins to glow with an inner light that spills out to heal his battle-worn companions. Chanting a song of glory, a dwarf swings his axe in wide swaths to cut through the ranks of orcs arrayed against him, shouting praise to the gods with every foe's fall. Calling down a curse upon the forces of undeath, a human lifts her holy symbol as light pours from it to drive back the zombies crowding in on her companions. Clerics are intermediaries between the mortal world and the distant planes of the gods. As varied as the gods they serve, clerics strive to em body the handiwork of their deities. No ordinary priest, a cleric is imbued with divine magic.",
   :saving_throws => ['Wis', 'Cha'],
   :hit_dice => '1d8',
   :hp_at_first_level => 8,
   :hp_at_first_level_attribute => 'Con',
   :hp_at_higher_levels => '1d8',
   :hp_at_higher_levels_min => 5,
   :hp_at_higher_levels_attribute => 'Con',
   :starting_equipment => {items: [
     {quantity: 1, choices: ['Mace', 'Warhammer']},
     {quantity: 1, choices: ['Scalemail', 'Leather Armor', 'Chainmail']},
     {quantity: 1, choices: ['Light Crossbow']},
     {quantity: 20, choices: ['Bolts']},
     {quantity: 1, choices: ["Priest's Pack", "Explorer's Pack"]},
     {quantity: 1, choices: ['Shield']},
     {quantity: 1, choices: ['Holy Symbol']},
   ]},
   :armor_prof => ['Light Armor', 'Medium Armor' 'Shield'],
   :weapon_prof => ['Simple Weapon'],
   :skill_prof => 2,
   :tool_prof => [],
   :skill_prof_choices => [6,7,10,14,15],
   :fund_modifier => 10,
   :fund_roll => '5d4'
  },
  {:name => 'Druid',
   :description => "A priest of the Old Faith, wielding the powers of nature - moonlight and plant growth, fire and lightning - and adopting animal forms",
   :image => 'druid.jpg',
   :primary_ability => 'Wis',
   :bio => "Holding high a gnarled staff wreathed with holly, an elf summons the fury of the storm and calls down explosive bolts of lightning to smite the torch-carrying orcs who threaten her forest. Crouching out of sight on a high tree branch in the form of a leopard, a human peers out of the jungle at the strange construction of a temple of Evil Elemental Air, keeping a close eye on the cultists’ activities. Swinging a blade form ed of pure fire, a half-elf charges into a mass of skeletal soldiers, sundering the unnatural magic that gives the foul creatures the mocking semblance of life. Whether calling on the elemental forces of nature or emulating the creatures of the animal world, druids are an embodiment of nature's resilience, cunning, and fury. They claim no mastery over nature. Instead, they see themselves as extensions of nature’s indomitable will.",
   :saving_throws => ['Int', 'Wis'],
   :hit_dice => '1d8',
   :hp_at_first_level => 8,
   :hp_at_first_level_attribute => 'Con',
   :hp_at_higher_levels => '1d8',
   :hp_at_higher_levels_min => 5,
   :hp_at_higher_levels_attribute => 'Con',
   :starting_equipment => {items: [
     {quantity: 1, choices: ['Wooden Shield', 'Any Simple Weapon']},
     {quantity: 1, choices: ['Scimitar' 'Any Simple Weapon']},
     {quantity: 1, choices: ['Leather Armor']},
     {quantity: 1, choices: ["Explorer's Pack"]},
     {quantity: 1, choices: ['Druidic Focus']}
   ]},
   :armor_prof => ['Light Armor', 'Medium Armor', 'Shield'],
   :weapon_prof => ['Club', 'Dagger', 'Dart', 'Javelin', 'Mace', 'Quarterstaff', 'Scimitar', 'Sickle', 'Sling', 'Spear'],
   :skill_prof => 2,
   :tool_prof => ['Herbalism Kit'],
   :skill_prof_choices => [2,7,10,11,12,15,18],
   :fund_modifier => 10,
   :fund_roll => '5d4'
  }
])
