Realm.create([
  {:name => "The Forgotten Realms",
   :description => "Dozens of deities are revered, worshiped, and feared throughout the world of the Forgotten Realms. At least thirty deities are widely known across the Realms, and many more are worshiped locally, by individual tribes, small cults, or certain sects of larger religious temples."
  },
  {:name => "Greyhawk",
   :description => "The gods of Greyhawk come from at least four different pantheons, representing the faiths of the various ethnic groups that populated the continent of Oerik over the ages. As a result, there's a great deal of overlap in their portfolios: Pelor is the Flan god of the sun and Pholtus is the Oeridian sun god, for example."
  },
  {:name => "Dragonlance",
   :description => "The gods of the world of Krynn are three families: seven gods of good headed by Paladine and Mishakal, seven of neutrality headed by Gilean, and seven of evil headed by Takhisis and Sargonnas. These deities have been called by many different names and held in varying levels of esteem by different peoples and cultures through the world's history, but they are the only gods of this world- their place fixed in the stars as constellations."
  },
  {:name => "Eberron",
   :description => "The world of Eberron has many different religions, but the most important revolves around a pantheon called the Sovereign Host and their malign shadow, the Dark Six. The gods of the Sovereign Host are thought to have dominion over every aspect of existence, and to speak with a unified voice. But the Dark Six are the primitive, bloody, and cruel gods who offer a dissenting voice. Eberron's other religions are very different from the traditional D&D pantheons. The monotheistic Church of the Silver Flame is devoted to fighting against evil in the world, but plagued by corruption in its own ranks. The philosophy of the Blood of Vol teaches that divinity lies within all mortal beings and reveres the undead who have secured that immortality. Various mad cults are devoted to the demons and horrors imprisoned in Eberron's Underdark (called Khyber, the Dragon Below). The followers of the Path of Light believe that the world is heading toward a glorious future where the shadows that cloud this world will be transformed into light. And two related nations of elves revere their ancestral spirits: the Undying Court, preserved as spirits or even undead forms, and the glorified Spirits of the Past, the great heroes of ancient wars."
  },
  {:name => "Nunhuman",
   :description => "Certain gods closely associated with nonhuman races are revered on many different worlds, though not always in the same way. The nonhuman races of the Forgotten Realms and Greyhawk share these deities. Nonhuman races often have whole pantheons of their own. Besides Moradin, for example, the dwarf gods include Moradin's wife, Berronar Truesilver, and a number of other gods thought to be their children and grandchildren: Abbathor, Clangeddin Silverbeard, Dugmaren Brightmantle, Dumathoin, Gorm Gullhyn, Haela Brightaxe, Marthammor Duin, Sharindlar, Thard Harr, and Vergadain. Individual clans and kingdoms of dwarves might revere some, ala, or none of these deities, and some have other gods unknown (or known by other names) to outsiders."
  },
  {:name => "Celtic Pantheon",
   :description => "It's said that something wild lurks in the heart of every soul, a space that thrills to the sound of geese calling all night, to the whispering wind through the pines, to the unexpected red of mistletoe on an oak-and it is in this space that the Celtic gods dwell. They sprang from the brook and stream, their might heightened by the strength of the oak and the beauty of the woodlands and open moor. When the first forester dared put a name to the face seen in the bole of a tree or the voice babbling in a brook, these gods forced themselves into being. The Celtic gods are as often served by druids as by clerics, for they are closely aligned with the forces of nature that druids revere."
  },
  {:name => "Greek Pantheon",
   :description => "The gods of Olympus make themselves known with the gentle lap of waves against the shores and the crash of the thunder among the cloud-enshrouded peaks. The thick boar-infested woods and the sere, olive-covered hillsides hold evidence of their passing. Every aspect of nature echoes with their presence, and they've made a place for themselves inside the human heart, too"
  },
  {:name => "Egyptian Pantheon",
   :description => "These gods are a young dynasty of an ancient divine family, heirs to the rulership of the cosmos and the maintenance of the divine principle of Ma'al - the fundamental order of truth, justice, law, and order that puts gods, mortal pharaohs, and ordinary men and women in their logical and rightful place in the universe. The Egyptian pantheon is unusual in having three gods with the Death domain of different alignments. Anubis is the lawful neutral god of the afterlife, who judges the souls of the dead. Set is a chaotic evil god of murder, perhaps best known for killing his brother Osiris. And Nephthys is a chaotic good goddess of mourning. Thus, although most clerics of the Death domain are villainous characters, clerics who serve Anubis or Nephthys need not be."
  },
  {:name => "Norse Pantheon",
   :description => "Where the land plummets from the snowy hills into the icy fjords below, where the longboats draw up on lo the beach, where the glaciers flow forward and retreat with every fall and spring - this is the land of the Vikings, the home of the Norse pantheon. It's a brutal clime, and one that calls for brutal living. The warriors of the land have had lo adapt to the harsh conditions in order to survive, but they haven't been too twisted by the needs of their environment. Given the necessity of raiding for food and wealth, it's surprising the mortals turned out as well as they did. Their powers reflect the need these warriors had for strong leadership and decisive action. Thus, they see their deities in every bend of a river, hear them in the crash of the thunder and the booming of the glaciers, and smell them in the smoke of a burning longhouse. The Norse pantheon includes two main families, the Aesir (deities of war and destiny) and the Vanir (gods of fertility and prosperity). Once enemies, these two families are now closely allied against their common enemies, the giants (including the gods Surtur and Thrym). Like the gods of Greyhawk, gods in different families sometimes have overlap in their spheres of influence: Frey (of the Vanir) and Odur (of the Aesir) are both associated with the sun, for example."
  }
])
