Deity.create([
  {:name => "Auril",
   :of => "Goddess of Winter",
   :alignment_id => 8,
   :suggested_domains => ['Nature', 'Tempest'],
   :symbol => "Six-pointed snowflake",
   :realm_id => 1,
  },
  {:name => "Azuth",
   :of => "God of Wizards",
   :alignment_id => 4,
   :suggested_domains => ['Knowledge'],
   :symbol => "Left hand pointing upward, outlined in fire",
   :realm_id => 1,
  },
  {:name => "Bane",
   :of => "God of Tyranny",
   :alignment_id => 7,
   :suggested_domains => ['War'],
   :symbol => "Upright black right hand, thumb and fingers together",
   :realm_id => 1,
  },
  {:name => "Beshaba",
   :of => "Goddess of Misfortune",
   :alignment_id => 9,
   :suggested_domains => ['Trickery'],
   :symbol => "Black antlers",
   :realm_id => 1,
  },
  {:name => "Bhaal",
   :of => "God of Murder",
   :alignment_id => 8,
   :suggested_domains => ['Death'],
   :symbol => "Skull surrounded by a ring of blood droplets",
   :realm_id => 1,
  },
  {:name => "Chauntea",
   :of => "Goddess of Agriculture",
   :alignment_id => 2,
   :suggested_domains => ['Life'],
   :symbol => "Sheaf of grain or a blooming rose over grain",
   :realm_id => 1,
  },
  {:name => "Cyric",
   :of => "God of Lies",
   :alignment_id => 9,
   :suggested_domains => ['Trickery'],
   :symbol => "White jawless skull on black or purple sunburst",
   :realm_id => 1,
  },
  {:name => "Deneir",
   :of => "God of Writing",
   :alignment_id => 2,
   :suggested_domains => ['Knowledge'],
   :symbol => "Lit candle above an open eye",
   :realm_id => 1,
  },
  {:name => "Eldath",
   :of => "Goddess of Peace",
   :alignment_id => 2,
   :suggested_domains => ['Life', 'Nature'],
   :symbol => "Waterfall plunging into a still pool",
   :realm_id => 1,
  },
  {:name => "Gond",
   :of => "God of Craft",
   :alignment_id => 5,
   :suggested_domains => ['Knowledge'],
   :symbol => "Toothed cog with four spokes",
   :realm_id => 1,
  },
  {:name => "Helm",
   :of => "God of Protection",
   :alignment_id => 4,
   :suggested_domains => ['Life', 'Light'],
   :symbol => "Staring eye on upright left gauntlet",
   :realm_id => 1,
  },
  {:name => "Ilmater",
   :of => "God of Endurance",
   :alignment_id => 1,
   :suggested_domains => ['Life'],
   :symbol => "Hand bounds at wrist with red cord",
   :realm_id => 1,
  },
  {:name => "Kelemvor",
   :of => "God of the Dead",
   :alignment_id => 4,
   :suggested_domains => ['Death'],
   :symbol => "Upright skeletal arm holding balanced scales",
   :realm_id => 1,
  },
  {:name => "Lathander",
   :of => "God of Birth and Renewal",
   :alignment_id => 2,
   :suggested_domains => ['Life', 'Light'],
   :symbol => "Road traveling into a sunrise",
   :realm_id => 1,
  },
  {:name => "Leira",
   :of => "Goddess of Illusion",
   :alignment_id => 9,
   :suggested_domains => ['Trickery'],
   :symbol => "Point-down triangle containing a swirl of mist",
   :realm_id => 1,
  },
  {:name => "Liira",
   :of => "Goddess of Joy",
   :alignment_id => 3,
   :suggested_domains => ['Life'],
   :symbol => "Triangle of three six-pointed stars",
   :realm_id => 1,
  },
  {:name => "Loviatar",
   :of => "Goddess of Pain",
   :alignment_id => 7,
   :suggested_domains => ['Death'],
   :symbol => "Nine-tailed barbed scourge",
   :realm_id => 1,
  },
  {:name => "Malar",
   :of => "God of the Hunt",
   :alignment_id => 9,
   :suggested_domains => ['Nature'],
   :symbol => "Clawed paw",
   :realm_id => 1,
  },
  {:name => "Mask",
   :of => "God of Thieves",
   :alignment_id => 6,
   :suggested_domains => ['Trickery'],
   :symbol => "Black mask",
   :realm_id => 1,
  },
  {:name => "Mielikki,",
   :of => "Goddess of Forests",
   :alignment_id => 2,
   :suggested_domains => ['Nature'],
   :symbol => "Unicorn's head",
   :realm_id => 1,
  },
  {:name => "Milil,",
   :of => "God of Poetry and Song",
   :alignment_id => 2,
   :suggested_domains => ['Light'],
   :symbol => "Five-stringed harp made of leaves",
   :realm_id => 1,
  },
  {:name => "Myrkul",
   :of => "God of Death",
   :alignment_id => 8,
   :suggested_domains => ['Death'],
   :symbol => "White human skull",
   :realm_id => 1,
  },
  {:name => "Mystra",
   :of => "Goddess of Magic",
   :alignment_id => 2,
   :suggested_domains => ['Knowledge'],
   :symbol => "Circle of seven stars, or nine stars encircling a flowing red mist, or a single star",
   :realm_id => 1,
  },
  {:name => "Oghma",
   :of => "God of Knowledge",
   :alignment_id => 5,
   :suggested_domains => ['Knowledge'],
   :symbol => "Blank scroll",
   :realm_id => 1,
  },
  {:name => "Savras",
   :of => "God of Divination and Fate",
   :alignment_id => 4,
   :suggested_domains => ['Knowledge'],
   :symbol => "Crystal ball containing many kinds of eyes",
   :realm_id => 1,
  },
  {:name => "Selune",
   :of => "Goddess of the Moon",
   :alignment_id => 3,
   :suggested_domains => ['Knowledge', 'Life'],
   :symbol => "Pair of eyes surrounded by seven stars",
   :realm_id => 1,
  },
  {:name => "Shar",
   :of => "Goddess of Darkness and Loss",
   :alignment_id => 8,
   :suggested_domains => ['Death', 'Trickery'],
   :symbol => "Black disk encircled with a border",
   :realm_id => 1,
  },
  {:name => "Silvanus",
   :of => "God of Wild Nature",
   :alignment_id => 5,
   :suggested_domains => ['Nature'],
   :symbol => "Oak leaf",
   :realm_id => 1,
  },
  {:name => "Sune",
   :of => "Goddess of Love and Beauty",
   :alignment_id => 3,
   :suggested_domains => ['Life', 'Light'],
   :symbol => "Face of a beautiful red-haired woman",
   :realm_id => 1,
  },
  {:name => "Talona",
   :of => "Goddess of Disease and Poison",
   :alignment_id => 9,
   :suggested_domains => ['Death'],
   :symbol => "Three teardrops on a triangle",
   :realm_id => 1,
  },
  {:name => "Talos",
   :of => "God of Storms",
   :alignment_id => 9,
   :suggested_domains => ['Tempest'],
   :symbol => "Three lightning bolts radiating from a central point",
   :realm_id => 1,
  },
  {:name => "Tempus",
   :of => "God of War",
   :alignment_id => 5,
   :suggested_domains => ['War'],
   :symbol => "Upright flaming sword",
   :realm_id => 1,
  },
  {:name => "Torm",
   :of => "God of Courage and Self-sacrifice",
   :alignment_id => 1,
   :suggested_domains => ['War'],
   :symbol => "White right gauntlet",
   :realm_id => 1,
  },
  {:name => "Tymora",
   :of => "Goddess of Good Fortune",
   :alignment_id => 3,
   :suggested_domains => ['Trickery'],
   :symbol => "Face-up coin",
   :realm_id => 1,
  },
  {:name => "Tyr",
   :of => "God of Justice",
   :alignment_id => 1,
   :suggested_domains => ['War'],
   :symbol => "Balanced scales resting on a warhammer",
   :realm_id => 1,
  },
  {:name => "Umberlee",
   :of => "Goddess of the Sea",
   :alignment_id => 9,
   :suggested_domains => ['Tempest'],
   :symbol => "Wave curling left and right",
   :realm_id => 1,
  },
  {:name => "Waukeen",
   :of => "Goddess of Trade",
   :alignment_id => 5,
   :suggested_domains => ['Knowledge', 'Trickery'],
   :symbol => "Upright coin with Waukeen's profile facing left",
   :realm_id => 1,
  }
])
