Alignment.create([
  {:name => 'Good',
   :axis => 'Lawful',
   :description => 'They can be counted on to do the right thing as expected by society. Gold dragons, paladins, and most dwarves are lawful good.'},
  {:name => 'Good',
   :axis => 'Neutral',
   :description => 'They do the best they can to help others according to their needs. Many celestials, some cloud giants, and most gnomes are neutral good.'},
  {:name => 'Good',
   :axis => 'Chaotic',
   :description => 'They act as their conscience directs, with little regard for what others expect. Copper dragons, many elves, and unicorns are chaotic good.'},
  {:name => 'Neutral',
   :axis => 'Lawful',
   :description => 'They act in accordance with law, tradition, or personal codes. Many monks and some wizards are lawful neutral.'},
  {:name => 'Neutral',
   :axis => 'True',
   :description => "The alignment of those who prefer to steer clear of moral questions and don't take sides, doing what seems best at the time. Lizardfolk, most druids, and many humans are neutral."},
  {:name => 'Neutral',
   :axis => 'Chaotic',
   :description => 'They follow their whims,holding their personal freedom above all else. Many barbarians and rogues, and some bards, are chaotic neutral.'},
  {:name => 'Evil',
   :axis => 'Lawful',
   :description => 'They methodically take what they want, within the limits of acode of tradition, loyalty, or order. Devils, blue dragons, and hobgoblins are lawful evil.'},
  {:name => 'Evil',
   :axis => 'Neutral',
   :description => 'The alignment of those who do whatever they can get away with, without compassion or qualms. Many drow, some cloud giants, and yugoloths are neutral evil.'},
  {:name => 'Evil',
   :axis => 'Chaotic',
   :description => 'They act with arbitrary violence, spurred by their greed, hatred, or bloodlust. Demons, red dragons, and orcs are chaotic evil.'},
])
Language.create([
  {:name => "Celestial",
   :description => "Described as beautiful, yet alien in nature, since it developed among beings with thought patterns very unlike those of humanity.",
   :html_class => 'Celestial'},
  {:name => "Common",
   :description => 'The common language. Pretty much English',
   :html_class => ""},
  {:name => "Draconic",
   :description => "Draconic is thought to be one of the oldest languages and is often used in the study of magic. The language sounds harsh to m ost other creatures and includes num erous hard consonants and sibilants.",
   :html_class => 'Draconic'},
  {:name => "Dwarvish",
   :description => "Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.",
   :html_class => 'Dwarvish'},
  {:name => "Elvish",
   :description => "Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poem s are fam ous am ong other races. Many bards learn their language so they can add Elvish ballads to their repertoires.",
   :html_class => "Elvish"},
  {:name => "Gnomish",
   :description => "The Gnomish language, which uses the Dwarvish script, is renow ned for its technical treatises and its catalogs of knowledge about the natural world.",
   :html_class => "Gnomish"},
  {:name => "Goblin",
   :description => "Also known as Ghukliak, was the language spoken by goblins, hobgoblins, and bugbears. It originally used the Dethek script, but by the late 15th century, goblinoids had begun using the Thorass alphabet instead.",
   :html_class => "Goblin"},
  {:name => "High Drowic",
   :description => "High Drow is a complex language and has a larger, runic alphabet. This language is primarily used by priestesses in their rituals and by nobles who wish not to be understood by lower-born drow and slaves",
   :html_class => "Drowic"},
  {:name => "Infernal",
   :description => "It is described as beautiful, yet alien in nature, since it developed among beings with thought patterns very unlike those of humanity.",
   :html_class => "Infernal"},
  {:name => "Theives Cant",
   :description => "A secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation.",
   :html_class => "Thieves"},
  {:name => "Undercommon",
   :description => "A trade language spoken by the majority of intelligent races native to the Underdark.",
   :html_class => "Undercommon"}
])
Feat.create([
  {:name => "Elemental Adept (Acid)",
   :description => 'You have a natural affinity for acid spells',
   :prereq_attribute => '',
   :prereq_min => 0,
   :prereq_other => 'The ability to cast at least one spell',
   :benefits => ["Spells you cast ignore resistance to acid damage. In addition, when you roll damage for a spell you cast that deals acid damage, you can treat any 1 on a damage die as a 2.",
                 "You can select this feat multiple times. Each time you do so, you must choose a different damage type."
                ]
  },
  {:name => "Elemental Adept (Cold)",
   :description => 'You have a natural affinity for cold spells',
   :prereq_attribute => '',
   :prereq_min => 0,
   :prereq_other => 'The ability to cast at least one spell',
   :benefits => ["Spells you cast ignore resistance to cold damage. In addition, when you roll damage for a spell you cast that deals cold damage, you can treat any 1 on a damage die as a 2.",
                 "You can select this feat multiple times. Each time you do so, you must choose a different damage type."
                ]
  },
  {:name => "Elemental Adept (Fire)",
   :description => 'You have a natural affinity for fire spells',
   :prereq_attribute => '',
   :prereq_min => 0,
   :prereq_other => 'The ability to cast at least one spell',
   :benefits => ["Spells you cast ignore resistance to fire damage. In addition, when you roll damage for a spell you cast that deals fire damage, you can treat any 1 on a damage die as a 2.",
                 "You can select this feat multiple times. Each time you do so, you must choose a different damage type."
                ]
  },
  {:name => "Elemental Adept (Lightning)",
   :description => 'You have a natural affinity for lightning spells',
   :prereq_attribute => '',
   :prereq_min => 0,
   :prereq_other => 'The ability to cast at least one spell',
   :benefits => ["Spells you cast ignore resistance to lightning damage. In addition, when you roll damage for a spell you cast that deals lightning damage, you can treat any 1 on a damage die as a 2.",
                 "You can select this feat multiple times. Each time you do so, you must choose a different damage type."
                ]
  },
  {:name => "Elemental Adept (Thunder)",
   :description => 'You have a natural affinity for thunder spells',
   :prereq_attribute => '',
   :prereq_min => 0,
   :prereq_other => 'The ability to cast at least one spell',
   :benefits => ["Spells you cast ignore resistance to thunder damage. In addition, when you roll damage for a spell you cast that deals thunder damage, you can treat any 1 on a damage die as a 2.",
                 "You can select this feat multiple times. Each time you do so, you must choose a different damage type."
                ]
  }
])
Skill.create([
  {:name => 'Acrobatics',
   :attrib => 'Dex',
   :description => "Your Dexterity check covers your attempt to stay on your feet in a tricky situation, such as when you’re trying to run across a sheet of ice, balance on a tightrope, or stay upright on a rocking ship's deck. The GM might also call for a Dexterity check to see if you can perform acrobatic stunts, including dives, rolls, somersaults, and flips."
  },
  {:name => 'Animal Handling',
   :attrib => 'Wis',
   :description => "When there is any question whether you can calm down a domesticated animal, keep a mount from getting spooked, or intuit an animal's intentions, the GM might call for a Wisdom check. You also make a Wisdom check to control your mount when you attempt a risky maneuver."
  },
  {:name => 'Arcana',
   :attrib => 'Int',
   :description => 'Your Intelligence check measures your ability to recall lore about spells, magic items, eldritch symbols, magical traditions, the planes of existence, and the inhabitants of those planes.'
  },
  {:name => 'Athletics',
   :attrib => 'Str',
   :description => 'Your Strength check covers difficult situations you encounter while climbing, jumping, or swimming.'
  },
  {:name => 'Deception',
   :attrib => 'Cha',
   :description => "Your Charisma check determines whether you can convincingly hide the truth, either verbally or through your actions. This deception can encompass everything from misleading others through ambiguity to telling outright lies. Typical situations include trying to fast-talk a guard, con a merchant, earn money through gambling, pass yourself off in a disguise, dull someone's suspicions with false assurances, or maintain a straight face while telling a blatant lie."
  },
  {:name => 'History',
   :attrib => 'Int',
   :description => 'Your Intelligence check measures your ability to recall lore about historical events, legendary people, ancient kingdoms, past disputes, recent wars, and lost civilizations.'
  },
  {:name => 'Insight',
   :attrib => 'Wis',
   :description => "Your Wisdom check decides whether you can determine the true intentions of a creature, such as when searching out a lie or predicting someone's next move. Doing so involves gleaning clues from body language, speech habits, and changes in mannerisms."
  },
  {:name => 'Intimidation',
   :attrib => 'Cha',
   :description => 'When you attempt to influence someone through overt threats, hostile actions, and physical violence, the GM might ask you to make a Charisma check. Examples include trying to pry information out of a prisoner, convincing street thugs to back down from a confrontation, or using the edge of a broken bottle to convince a sneering vizier to reconsider a decision.'
  },
  {:name => 'Investigation',
   :attrib => 'Int',
   :description => 'When you look around for clues and make deductions based on those clues, you make an Intelligence check. You might deduce the location of a hidden object, discern from the appearance of a wound what kind of weapon dealt it, or determine the weakest point in a tunnel that could cause it to collapse. Poring through ancient scrolls in search of a hidden fragment of knowledge might also call for an Intelligence check.'
  },
  {:name => 'Medicine',
   :attrib => 'Wis',
   :description => 'A Wisdom check lets you try to stabilize a dying companion or diagnose an illness.'
  },
  {:name => 'Nature',
   :attrib => 'Int',
   :description => 'Your Intelligence check measures your ability to recall lore about terrain, plants and animals, the weather, and natural cycles.'
  },
  {:name => 'Perception',
   :attrib => 'Wis',
   :description => 'Your Wisdom check lets you spot, hear, or otherwise detect the presence of something. It measures your general awareness of your surroundings and the keenness of your senses. For example, you might try to hear a conversation through a closed door, eavesdrop under an open window, or hear monsters moving stealthily in the forest. Or you might try to spot things that are obscured or easy to miss, whether they are orcs lying in ambush on a road, thugs hiding in the shadows of an alley, or candlelight under a closed secret door.'
  },
  {:name => 'Performance',
   :attrib => 'Cha',
   :description => 'Your Charisma check determines how well you can delight an audience with music, dance, acting, storytelling, or some other form of entertainment.'
  },
  {:name => 'Persuasion',
   :attrib => 'Cha',
   :description => 'When you attempt to influence someone or a group of people with tact, social graces, or good nature, the GM might ask you to make a Charisma check. Typically, you use persuasion when acting in good faith, to foster friendships, make cordial requests, or exhibit proper etiquette. Examples of persuading others include convincing a chamberlain to let your party see the king, negotiating peace between warring tribes, or inspiring a crowd of townsfolk.'
  },
  {:name => 'Religion',
   :attrib => 'Int',
   :description => 'Your Intelligence check measures your ability to recall lore about deities, rites and prayers, religious hierarchies, holy symbols, and the practices of secret cults.'
  },
  {:name => 'Sleight of Hand',
   :attrib => 'Dex',
   :description => "Whenever you attempt an act of legerdemain or manual trickery, such as planting something on someone else or concealing an object on your person, make a Dexterity check. The GM might also call for a Dexterity check to determine whether you can lift a coin purse off another person or slip something out of another person's pocket."
  },
  {:name => 'Stealth',
   :attrib => 'Dex',
   :description => 'Make a Dexterity check when you attempt to conceal yourself from enemies, slink past guards, slip away without being noticed, or sneak up on someone without being seen or heard.'
  },
  {:name => 'Survival',
   :attrib => 'Wis',
   :description => 'The GM might ask you to make a Wisdom check to follow tracks, hunt wild game, guide your group through frozen wastelands, identify signs that owlbears live nearby, predict the weather, or avoid quicksand and other natural hazards.'
  }
])
Size.create([
  {:name => 'Tiny'},
  {:name => 'Small'},
  {:name => 'Medium'},
  {:name => 'Large'},
  {:name => 'Huge'},
  {:name => 'Gargantuan'}
])
Race.create([
  {:name => 'Dragonborn',
   :bio => 'Born of dragons, as their name proclaims, the dragonborn walk proudly through a world that greets them with fearful incomprehension. Shaped by draconic gods or the dragons themselves, dragonborn originally hatched from dragon eggs as a unique race, combining the best attributes of dragons and humanoids. Some dragonborn are faithful servants to true dragons, others form the ranks of soldiers in great wars, and still others find themselves adrift, with no clear calling in life. Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail. The first dragonborn had scales of vibrant hues matching the colors of their dragon kin, but generations of interbreeding have created a more uniform appearance. Their small, fine scales are usually brass or bronze in color, sometimes ranging to scarlet, rust, gold, or copper-green. They are tall and strongly built, often standing close to 6 1/2 feet tall and weighing 300 pounds or more. Their hands and feet are strong, talonlike claws with three fingers and a thumb on each hand. A continual drive for self-improvement reflects the self-sufficiency of the race as a whole. Dragonborn value skill and excellence in all endeavors. They hate to fail, and they push them selves to extreme efforts before they give up on something. A dragonborn holds mastery of a particular skill as a lifetime goal. Members of other races who share the same commitment find it easy to earn the respect of a dragonborn. Though all dragonborn strive to be self-sufficient, they recognize that help is sometimes needed in difficult situations. But the best source for such help is the clan, and when a clan needs help, it turns to another dragonborn clan before seeking aid from other races—or even from the gods.',
   :image => 'dragonborn.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Draconic'],
   :traits => ['Draconic Ancestry',
               'Breath Weapon',
               'Damage Resistance'],
   :description => 'Born of dragons, as their name proclaims, the dragonborn walk proudly through a world that greets them with fearful incomprehension. Shaped by draconic gods or the dragons themselves, dragonborn originally hatched from dragon eggs as a unique race, combining the best attributes of dragons and humanoids.',
   :age_info => 'Young dragonborn grow quickly. They walk hours after hatching, attain the size and development of a 10-year-old human child by the age of 3, and reach adulthood by 15. They live to be around 80.',
   :size_info => 'Dragonborn are taller and heavier than humans, standing well over 6 feet tall and averaging almost 250 pounds.',
   :size_id => 3,
   :str => 2,
   :dex => 0,
   :con => 0,
   :wis => 0,
   :int => 0,
   :cha => 1,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 66,
   :base_weight =>175,
   :height_mod => '2d8',
   :weight_mod => '2d6'
  },
  {:name => 'Hill Dwarf',
   :bio => "Kingdoms rich in ancient grandeur, halls carved into the roots of mountains, the echoing of picks and hammers in deep mines and blazing forges, a commitment to clan and tradition, and a burning hatred of goblins and orcs—these common threads unite dwarves across the multiverse, the heritage of every dwarf character. Dwarves respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and do not abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge. Dwarves who take up the adventuring life might be motivated by a desire for treasure—for its own sake, for a specific purpose, or even out of an altruistic desire to help others. Other dwarves are driven by the command or inspiration of a deity, a direct calling or simply a desire to bring glory to one of the dwarf gods. Clan and ancestry are also important motivators. A dwarf might seek to restore a clan’s lost honor, avenge an ancient wrong his or her clan suffered, or earn a new place within the clan after having been exiled. Or a dwarf might search for the axe wielded by a mighty ancestor, lost on the field of battle centuries ago. As a hill dwarf, you have keen senses, deep intuition, and remarkable resilience. The gold dwarves of Faerun in their mighty southern kingdom are hill dwarves, as are the exiled Neidar and the debased Klar of Krynn in the Dragonlance setting.",
   :image => 'dwarf.png',
   :speed => 25,
   :languages => ['Common',
                  'Dwarvish'],
   :traits => ['Darkvision',
               'Dwarven Resilience',
               'Dwarven Combat Training',
               'Tool Proficiency',
               'Stonecutting',
               'Dwarven Toughness'],
   :description => "Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change.",
   :age_info => 'Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.',
   :size_info => 'Dwarves stand between 4 and 5 feet tall and average about 150 pounds.',
   :size_id => 3,
   :str => 0,
   :dex => 0,
   :con => 2,
   :wis => 1,
   :int => 0,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 44,
   :base_weight => 115,
   :height_mod => '2d4',
   :weight_mod => '2d6'
  },
  {:name => 'Mountain Dwarf',
   :bio => "Kingdoms rich in ancient grandeur, halls carved into the roots of mountains, the echoing of picks and hammers in deep mines and blazing forges, a commitment to clan and tradition, and a burning hatred of goblins and orcs—these common threads unite dwarves across the multiverse, the heritage of every dwarf character. Dwarves respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and do not abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge. Dwarves who take up the adventuring life might be motivated by a desire for treasure—for its own sake, for a specific purpose, or even out of an altruistic desire to help others. Other dwarves are driven by the command or inspiration of a deity, a direct calling or simply a desire to bring glory to one of the dwarf gods. Clan and ancestry are also important motivators. A dwarf might seek to restore a clan’s lost honor, avenge an ancient wrong his or her clan suffered, or earn a new place within the clan after having been exiled. Or a dwarf might search for the axe wielded by a mighty ancestor, lost on the field of battle centuries ago. As a mountain dwarf, you're strong and hardy, accustom ed to a difficult life in rugged terrain. You’re probably on the tall side (for a dwarf), and tend toward lighter coloration. The shield dwarves of northern Faerun, as well as the ruling Hylar clan and the noble Daewar clan of Dragonlance, are mountain dwarves.",
   :image => 'dwarf.png',
   :speed => 25,
   :languages => ['Common',
                  'Dwarvish'],
   :traits => ['Darkvision',
               'Dwarven Resilience',
               'Dwarven Combat Training',
               'Tool Proficiency',
               'Stonecutting',
               'Dwarven Armor Training'],
   :description => 'Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change.',
   :age_info => 'Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.',
   :size_info => 'Dwarves stand between 4 and 5 feet tall and average about 150 pounds.',
   :size_id => 3,
   :str => 2,
   :dex => 0,
   :con => 2,
   :wis => 0,
   :int => 0,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 48,
   :base_weight => 130,
   :height_mod => '2d4',
   :weight_mod => '2d6'
  },
  {:name => 'Drow',
   :bio => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorterlived races more deeply. They are m ore often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance. Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and m agic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining). Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes. Descended from an earlier subrace of dark-skinned elves, the drow were banished from the surface world for following the goddess Lolth down the path to evil and corruption. Now they have built their own civilization in the depths of the Underdark, patterned after the Way of Lolth. Also called dark elves, the drow have black skin that resem bles polished obsidian and stark white or pale yellow hair. They commonly have very pale eyes (so pale as to be mistaken for white) in shades of lilac, silver, pink, red, and blue. They tend to be smaller and thinner than most elves.",
   :image => 'elf.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Elvish'],
   :traits => ['Superior Darkvision',
               'Keen Senses',
               'Fey Ancestry',
               'Trance',
               'Sunlight Sensitivity',
               'Drow Magic',
               'Drow Weapon Training'],
   :description => 'Elves are a magical people of otherworldly grace, living in the w orld but not entirely part of it. Elves love nature and magic, art and artistry, music and poetry, and the good things of the world.',
   :age_info => "Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old",
   :size_info => "Elves range from under 5 to over 6 feet tall and have slender builds.",
   :size_id => 3,
   :str => 0,
   :dex => 2,
   :con => 0,
   :wis => 0,
   :int => 0,
   :cha => 1,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 53,
   :base_weight => 75,
   :height_mod => '2d6',
   :weight_mod => '1d6'
  },
  {:name => 'High Elf',
   :bio => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorterlived races more deeply. They are m ore often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance. Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and m agic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining). Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes As a high elf, you have a keen mind and a mastery of at least the basics of magic. In many of the worlds of D&D, there are two kinds of high elves. One type (which includes the gray elves and valley elves of Greyhawk, the Silvanesti of Dragonlance, and the sun elves of the Forgotten Realms) is haughty and reclusive, believing themselves to be superior to non-elves and even other elves. The other type (including the high elves of Greyhawk. the Qualinesti of Dragonlance, and the moon elves of the Forgotten Realms) are more common and more friendly, and often encountered among humans and other races. The sun elves of Faerun (also called gold elves or sunrise elves) have bronze skin and hair of copper, black, or golden blond. Their eyes are golden, silver, or black. Moon elves (also called silver elves or gray elves) are much paler, with alabaster skin som etim es tinged with blue. They often have hair of silver-white, black, or blue, but various shades of blond, brown, and red are not uncommon. Their eyes are blue or green and flecked with gold.",
   :image => 'elf.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Elvish'],
   :traits => ["Darkvision",
               "Keen Senses",
               "Fey Ancestry",
               "Trance",
               "Elf Weapon Training",
               "Cantrip"],
   :description => 'Elves are a magical people of otherworldly grace, living in the w orld but not entirely part of it. Elves love nature and magic, art and artistry, music and poetry, and the good things of the world.',
   :age_info => 'Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old',
   :size_info => 'Elves range from under 5 to over 6 feet tall and have slender builds.',
   :size_id => 3,
   :str => 0,
   :dex => 2,
   :con => 0,
   :wis => 0,
   :int => 1,
   :cha => 0,
   :free_points => 0,
   :free_languages => 1,
   :base_height => 54,
   :base_weight => 90,
   :height_mod => '2d10',
   :weight_mod => '1d4'
  },
  {:name => 'Wood Elf',
   :bio => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorterlived races more deeply. They are m ore often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance. Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and m agic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining). Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes. As a wood elf, you have keen senses and intuition, and your fleet feet carry you quickly and stealthily through your native forests. This category includes the wild elves (grugach) of Greyhawk and the Kagonesti of Dragonlance, as well as the races called wood elves in Greyhawk and the Forgotten Realms. In Faerun, wood elves (also called wild elves, green elves, or forest elves) are reclusive and distrusting of non-elves. Wood elves’ skin tends to be copperish in hue, sometimes with traces of green. Their hair tends toward browns and blacks, but it is occasionally blond or copper-colored. Their eyes are green, brown, or hazel.",
   :image => 'elf.jpg',
   :speed => 35,
   :languages => ['Common',
                  'Elvish'],
   :traits => ["Darkvision",
               "Keen Senses",
               "Fey Ancestry",
               "Trance",
               "Elf Weapon Training",
               "Fleet of Foot",
               "Mask of the Wild"],
   :description => 'Elves are a magical people of otherworldly grace, living in the w orld but not entirely part of it. Elves love nature and magic, art and artistry, music and poetry, and the good things of the world.',
   :age_info => 'Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.',
   :size_info => 'Elves range from under 5 to over 6 feet tall and have slender builds.',
   :size_id => 3,
   :str => 0,
   :dex => 2,
   :con => 0,
   :wis => 1,
   :int => 0,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 54,
   :base_weight => 100,
   :height_mod => '2d10',
   :weight_mod => '1d4'
  },
  {:name => 'Forest Gnome',
   :bio => "As far as gnomes are concerned, being alive is a wonderful thing, and they squeeze every ounce of enjoyment out of their three to five centuries of life. Humans might wonder about getting bored over the course of such a long life, and elves take plenty of time to savor the beauties of the world in their long years, but gnomes seem to worry that even with all that time, they can’t get in enough of the things they want to do and see. Gnomes make their homes in hilly, wooded lands. They live underground but get more fresh air than dwarves do, enjoying the natural, living world on the surface whenever they can. Their homes are well hidden by both clever construction and simple illusions. Welcome visitors are quickly ushered into the bright, warm burrows. Those who are not welcome are unlikely to find the burrows in the first place. Gnomes love names, and most have half a dozen or so. A gnome's mother, father, clan elder, aunts, and uncles each give the gnome a name, and various nicknames from just about everyone else might or might not stick over time. Gnome names are typically variants on the names of ancestors or distant relatives, though some are purely new inventions. When dealing with humans and others who are 'stuffy' about names, a gnome learns to use no more than three names: a personal name, a clan name, and a nickname, choosing the one in each category that’s the most fun to say. As a forest gnome, you have a natural knack for illusion and inherent quickness and stealth. In the worlds of D&D, forest gnomes are rare and secretive. They gather in hidden com m unities in sylvan forests, using illusions and trickery to conceal themselves from threats or to mask their escape should they be detected. Forest gnomes tend to be friendly with other good-spirited woodland folk, and they regard elves and good fey as their most important allies. These gnomes also befriend small forest animals and rely on them for information about threats that might prowl their lands.",
   :image => 'gnome.jpg',
   :speed => 25,
   :languages => ['Common',
                  'Gnomish'],
   :traits => ['Darkvision',
               'Gnome Cunning',
               'Natural Illusionist',
               'Speak with Small Beasts'],
   :description => "Gnomes take delight in life, enjoying every moment of invention, exploration, investigation, creation, and play.",
   :age_info => 'Gnomes mature at the same rate humans do, and most are expected to settle down into an adult life by around age 40. They can live 350 to almost 500 years.',
   :size_info => 'Gnomes are between 3 and 4 feet tall and average about 40 pounds.',
   :size_id => 2,
   :str => 0,
   :dex => 1,
   :con => 0,
   :wis => 0,
   :int => 2,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 35,
   :base_weight => 35,
   :height_mod => '2d4',
   :weight_mod => '1'
  },
  {:name => 'Rock Gnome',
   :bio => "As far as gnomes are concerned, being alive is a wonderful thing, and they squeeze every ounce of enjoyment out of their three to five centuries of life. Humans might wonder about getting bored over the course of such a long life, and elves take plenty of time to savor the beauties of the world in their long years, but gnomes seem to worry that even with all that time, they can’t get in enough of the things they want to do and see. Gnomes make their homes in hilly, wooded lands. They live underground but get more fresh air than dwarves do, enjoying the natural, living world on the surface whenever they can. Their homes are well hidden by both clever construction and simple illusions. Welcome visitors are quickly ushered into the bright, warm burrows. Those who are not welcome are unlikely to find the burrows in the first place. Gnomes love names, and most have half a dozen or so. A gnome's mother, father, clan elder, aunts, and uncles each give the gnome a name, and various nicknames from just about everyone else might or might not stick over time. Gnome names are typically variants on the names of ancestors or distant relatives, though some are purely new inventions. When dealing with humans and others who are 'stuffy' about names, a gnome learns to use no more than three names: a personal name, a clan name, and a nickname, choosing the one in each category that’s the most fun to say. As a rock gnome, you have a natural inventiveness and hardiness beyond that of other gnomes. Most gnomes in the worlds of D&D are rock gnomes, including the tinker gnomes of the Dragonlance setting.",
   :image => 'gnome.jpg',
   :speed => 25,
   :languages => ['Common',
                  'Gnomish'],
   :traits => ['Darkvision',
               'Gnome Cunning',
               "Artificer's Lore",
               "Tinker"],
   :description => 'Gnomes take delight in life, enjoying every moment of invention, exploration, investigation, creation, and play.',
   :age_info => 'Gnomes mature at the same rate humans do, and most are expected to settle down into an adult life by around age 40. They can live 350 to almost 500 years',
   :size_info => 'Gnomes are between 3 and 4 feet tall and average about 40 pounds.',
   :size_id => 2,
   :str => 0,
   :dex => 0,
   :con => 1,
   :wis => 0,
   :int => 2,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 35,
   :base_weight => 35,
   :height_mod => '2d4',
   :weight_mod => '1'
  },
  {:name => 'Half-Elf',
   :bio => "Walking in two worlds but truly belonging to neither, half-elves combine what some say are the best qualities of their elf and human parents: human curiosity, inventiveness, and ambition tempered by the refined senses, love of nature, and artistic tastes of the elves. So e half-elves live among humans, set apart by their emotional and physical differences, watching friends and loved ones age while time barely touches them. Others live with the elves, growing restless as they reach adulthood in the timeless elven realms, while their peers continue to live as children. Many half-elves, unable to fit into either society, choose lives of solitary wandering or join with other misfits and outcasts in the adventuring life. Half-elves have no lands of their own, though they are welcome in human cities and somewhat less welcome in elven forests. In large cities in regions where elves and humans interact often, half-elves are sometimes numerous enough to form small communities of their own. They enjoy the company of other half-elves, the only people who truly understand what it is to live between these two worlds. In most parts of the world, though, half-elves are uncommon enough that one might live for years without meeting another. Some half-elves prefer to avoid company altogether, wandering the wilds as trappers, foresters, hunters, or adventurers and visiting civilization only rarely. Like elves, they are driven by the wanderlust that comes of their longevity. Others, in contrast, throw themselves into the thick of society, putting their charisma and social skills to great use in diplomatic roles or as swindlers.",
   :image => 'half-elf.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Elvish'],
   :traits => ['Darkvision',
               'Fey Ancestry',
               'Skill Versatility'],
   :description => 'To humans, half-elves look like elves, and to elves, they look human. In height, they’re on par with both parents, though they’re neither as slender as elves nor as broad as humans.',
   :age_info => 'Half-elves mature at the same rate humans do and reach adulthood around the age of 20. They live much longer than humans, however, often exceeding 180 years.',
   :size_info => 'Half-elves are about the same size as humans, ranging from 5 to 6 feet tall.',
   :size_id => 3,
   :str => 0,
   :dex => 0,
   :con => 0,
   :wis => 0,
   :int => 0,
   :cha => 2,
   :free_points => 2,
   :free_languages => 1,
   :base_height => 57,
   :base_weight => 110,
   :height_mod => '2d8',
   :weight_mod => '2d4'
  },
  {:name => 'Half-Orc',
   :bio => "Orcs regard battle scars as tokens of pride and ornamental scars as things of beauty. Other scars, though, mark an orc or half-orc as a former slave or a disgraced exile. Any half-orc who has lived among or near orcs has scars, whether they are marks of humiliation or of pride, recounting their past exploits and injuries. Such a half-orc living among humans might display these scars proudly or hide them in shame. The one-eyed god Gruumsh created the orcs, and even those orcs who turn away from his worship can’t fully escape his influence. The same is true of half-orcs, though their human blood moderates the impact of their orcish heritage. Some half-orcs hear the whispers of Gruumsh in their dreams, calling them to unleash the rage that simm ers within them. Others feel Gruumsh’s exultation when they join in melee combat—and either exult along with him or shiver with fear and loathing. Half-orcs are not evil by nature, but evil does lurk within them, whether they embrace it or rebel against it. Half-orcs most often live among orcs. Of the other races, humans are most likely to accept half-orcs, and halforcs almost always live in human lands when not living among orc tribes. Whether proving themselves among rough barbarian tribes or scrabbling to survive in the slums of larger cities, half-orcs get by on their physical might, their endurance, and the sheer determination they inherit from their human ancestry.",
   :image => 'half-orc.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Dwarvish'],
   :traits => ['Darkvision',
               'Menacing',
               'Relentless Endurance',
               'Savage Attacks'],
   :description => 'Orc and human tribes sometimes form alliances, joining forces into a larger horde to the terror of civilized lands nearby. When these alliances are sealed by marriages, half-orcs are born.',
   :age_info => 'Half-orcs mature a little faster than humans, reaching adulthood around age 14. They age noticeably faster and rarely live longer than 75 years.',
   :size_info => 'Half-orcs are somewhat larger and bulkier than humans, and they range from 5 to well over 6 feet tall.',
   :size_id => 3,
   :str => 2,
   :dex => 0,
   :con => 1,
   :wis => 0,
   :int => 0,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 58,
   :base_weight => 140,
   :height_mod => '2d10',
   :weight_mod => '2d6'
  },
  {:name => 'Halfling Lightfoot',
   :bio => "Halflings are adept at fitting into a community of humans, dwarves, or elves, making themselves valuable and welcome. The combination of their inherent stealth and their unassuming nature helps halflings to avoid unwanted attention. The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear relatively harm less and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. Halflings work readily with others, and they are loyal to their friends, whether halfling or otherwise. They can display remarkable ferocity when their friends, families, or communities are threatened. As a lightfoot halfling, you can easily hide from notice, even using other people as cover. You’re inclined to be affable and get along well with others. In the Forgotten Realms, lightfoot halflings have spread the farthest and thus are the most common variety. Lightfoots are more prone to wanderlust than other halflings, and often dwell alongside other races or take up a nomadic life. In the world of Greyhawk, these halflings are called hairfeet or tallfellows.",
   :image => 'halfling.jpg',
   :speed => 25,
   :languages => ['Common'],
   :traits => ['Lucky',
               'Brave',
               'Halfling Nimbleness',
               'Naturally Stealthy'],
   :description => 'Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory.',
   :age_info => 'A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.',
   :size_info => 'Halflings average about 3 feet tall and weigh about 40 pounds.',
   :size_id => 2,
   :str => 0,
   :dex => 2,
   :con => 0,
   :wis => 0,
   :int => 0,
   :cha => 1,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 31,
   :base_weight => 35,
   :height_mod => '2d4',
   :weight_mod => '1'
  },
  {:name => 'Halfling Scout',
   :bio => "Halflings are adept at fitting into a community of humans, dwarves, or elves, making themselves valuable and welcome. The combination of their inherent stealth and their unassuming nature helps halflings to avoid unwanted attention. The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear relatively harm less and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. Halflings work readily with others, and they are loyal to their friends, whether halfling or otherwise. They can display remarkable ferocity when their friends, families, or communities are threatened. As a stout halfling, you’re hardier than average and have some resistance to poison. Some say that stouts have dwarven blood. In the Forgotten Realms, these halflings are called stronghearts, and they’re most common in the south.",
   :image => 'halfling.jpg',
   :speed => 25,
   :languages => ['Common'],
   :traits => ['Lucky',
               'Brave',
               'Halfling Nimbleness',
               'Stout Resilience'],
   :description => 'Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory.',
   :age_info => 'A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.',
   :size_info => 'Halflings average about 3 feet tall and weigh about 40 pounds.',
   :size_id => 2,
   :str => 0,
   :dex => 2,
   :con => 1,
   :wis => 0,
   :int => 0,
   :cha => 0,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 31,
   :base_weight => 35,
   :height_mod => '2d4',
   :weight_mod => '1'
  },
  {:name => 'Human',
   :bio => "In the reckonings of most worlds, humans are the youngest of the common races, late to arrive on the world scene and short-lived in comparison to dwarves, elves, and dragons. Perhaps it is because of their shorter lives that they strive to achieve as much as they can in the years they are given. Or maybe they feel they have something to prove to the elder races, and that’s why they build their mighty empires on the foundation of conquest and trade. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds. Where a single elf or dwarf might take on the responsibility of guarding a special location or a powerful secret, humans found sacred orders and institutions for such purposes. While dwarf clans and halfling elders pass on the ancient traditions to each new generation, human temples, governments, libraries, and codes of law fix their traditions in the bedrock of history. Humans dream of immortality, but (except for those few who seek undeath or divine ascension to escape death’s clutches) they achieve it by ensuring that they will be remembered when they are gone. Humans who seek adventure are the most daring and ambitious members of a daring and ambitious race. They seek to earn glory in the eyes of their fellows by amassing power, wealth, and fame. More than other people, humans champion causes rather than territories or groups.",
   :image => 'human.jpg',
   :speed => 30,
   :languages => ['Common'],
   :traits => [],
   :description => 'Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled.',
   :age_info => 'Humans reach adulthood in their late teens and live less than a century.',
   :size_info => 'Humans vary widely in height and build, from barely 5 feet to well over 6 feet tall.',
   :size_id => 3,
   :str => 1,
   :dex => 1,
   :con => 1,
   :wis => 1,
   :int => 1,
   :cha => 1,
   :free_points => 0,
   :free_languages => 1,
   :base_height => 56,
   :base_weight => 110,
   :height_mod => '2d10',
   :weight_mod => '2d4'
  },
  {:name => 'Tiefling',
   :bio => "To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling. And to twist the knife, tieflings know that this is because a pact struck generations ago infused the essence of Asmodeus—overlord of the Nine Hells—into their bloodline. Their appearance and their nature are not their fault but the result of an ancient sin, for which they and their children and their children’s children will always be held accountable. Tieflings subsist in small minorities found mostly in human cities or towns, often in the roughest quarters of those places, where they grow up to be swindlers, thieves, or crime lords. Sometimes they live among other minority populations in enclaves where they are treated with more respect. Lacking a homeland, tieflings know that they have to make their own way in the world and that they have to be strong to survive. They are not quick to trust anyone who claims to be a friend, but when a tiefling’s companions demonstrate that they trust him or her, the tiefling learns to extend the same trust to them. And once a tiefling gives someone loyalty, the tiefling is a firm friend or ally for life.",
   :image => 'tiefling.jpg',
   :speed => 30,
   :languages => ['Common',
                  'Infernal'],
   :traits => ['Darkvision',
               'Hellish Resistance',
               'Infernal Legacy'],
   :description => 'Tieflings are derived from human bloodlines, and in the broadest possible sense, they still look human. However, their infernal heritage has left a clear imprint on their appearance.',
   :age_info => 'Tieflings mature at the same rate as humans but live a few years longer.',
   :size_info => 'Tieflings are about the same size and build as humans.',
   :size_id => 3,
   :str => 0,
   :dex => 0,
   :con => 0,
   :wis => 0,
   :int => 1,
   :cha => 2,
   :free_points => 0,
   :free_languages => 0,
   :base_height => 57,
   :base_weight => 110,
   :height_mod => '2d8',
   :weight_mod => '2d4'
  }
])
Trait.create([
  {:name => 'Draconic Ancestry',
   :description => 'You have draconic ancestry. Choose one type of dragon from the Draconic Ancestry table. Your breath weapon and damage resistance are determined by the dragon type, as shown in the table.',
   :table => {
     headers: ["Dragon", "Damage Type", "Breath Weapon"],
     rows: [
       ["Black", "Acid", "5 by 30 ft line (Dex save)"],
       ["Blue", "Lightning", "5 by 30 ft line (Dex save)"],
       ["Brass", "Fire", "5 by 30 ft line (Dex save)"],
       ["Bronze", "Lightning", "5 by 30 ft line (Dex save)"],
       ["Copper", "Acid", "5 by 30 ft line (Dex save)"],
       ["Gold", "Fire", "15 ft cone (Dex save)"],
       ["Green", "Poison", "15 ft cone (Con save)"],
       ["Red", "Fire", "15 ft cone (Dex save)"],
       ["Silver", "Cold", "15 ft cone (Con save)"],
       ["White", "Cold", "15 ft cone (Con save)"]
     ]
   },
   :race_id => 1,
  },
  {:name => 'Breath Weapon',
   :description => 'You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, and 5d6 at 16th level. After you use your breath weapon, you can’t use it again until you com plete a short or long rest.',
   :table => {},
   :race_id => 1
  },
  {:name => 'Damage Resistance',
   :description => 'You have resistance to the damage type associated with your draconic ancestry.',
   :table => {},
   :race_id => 1
  }
])
Feature.create([
  {:name => 'Shelter of the Faithful',
   :description => 'As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle. You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there, This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home, While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.',
   :table => {},
   :race_id => '',
   :class_id => '',
  },
  {:name => 'Frenzy',
   :description => 'Starting when you choose this path at level 3, you can go into a frenzy when you rage. If you do so, for the duration of your rage you can make a single melee weapon attack as a bonus action on each of your turns after this one. When your rage ends, you suffer one level of exhaustion.',
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Mindless Rage',
   :description => "Beginning at the 6th level, you can't be charmed or frightened while raging. If you are charm ed or frightened when you enter your rage, the effect is suspended for the duration of the rage.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Intimidating Presence',
   :description => "Beginning at the 10th level, you can use your action to frighten someone with your menacing presence. When you do so, choose one creature that you can see within 30 feet of you. If the creature can see or hear you, it must succeed on a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Charisma modifier) or be frightened of you until the end of your next turn. On subsequent turns, you can use your action to extend the duration of this effect on the frightened creature until the end of your next turn. This effect ends if the creature ends its turn out of line of sight or more than 60 feet away from you. If the creature succeeds on its saving throw, you can't use this feature on that creature again for 24 hours.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Retaliation',
   :description => 'Starting at the 14th level, when you take damage from a creature that is within 5 feet of you, you can use your reaction to make a melee weapon attack against that creature.',
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Rage',
   :description => "In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren't wearing heavy armor:<ul><li>You have advantage on Strength checks and Strength saving throws.</li><li>When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, as shown in the Rage Damage column of the Barbarian table.</li><li>You have resistance to bludgeoning, piercing, and slashing damage.</li></ul>If you are able to cast spells, you can’t cast them or concentrate on them while raging. Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven’t attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action. Once you have raged the number of times shown for your barbarian level in the Rages column of the Barbarian table, you must finish a long rest before you can rage again.",
   :table => {},
   :race_id => '',
   :class_id => 1
  },
  {:name => 'Unarmored Defense',
   :description => "While you are not wearing any armor, your Arm or Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.",
   :table => {},
   :race_id => '',
   :class_id => 1
  }
])
Background.create([
  {:name => 'Acolyte',
   :description => 'You have spent your life in the service of a temple to a specific god or pantheon of gods, You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric-performing sacred rites is not the same thing as channeling divine power. Choose a god, a pantheon of gods, or some other quasi-divine being, and work with your DM to detail the nature of your religious service. Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites? Or were you a high priest who suddenly experienced a call to serve your god in a different way? Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny.',
   :skill_prof => [7,15],
   :tool_prof => [],
   :equipment => {items: [
     {quantity: 1, choices: ['Holy Symbol']},
     {quantity: 1, choices: ['Prayer Book', 'Prayer Wheel']},
     {quantity: 5, choices: ['Stick of Incense']},
     {quantity: 1, choices: ['Vestament']},
     {quantity: 1, choices: ['Common Clothes']},
     {quantity: 1, choices: ['Belt Pouch']},
     {quantity: 15, choices: ['GP']}
   ]},
   :languages => [],
   :language_points => 2,
   :feature_id => 1
  }
])
PersonalityTrait.create([
  {:description => "I idolize a particular hero of my faith, and constantly refer to that person's deeds and examples.",
   :background_id => 1
  },
  {:description => "I can find common ground between the fiercest enemies, empathizing with them and always working towards peace.",
   :background_id => 1
  },
  {:description => "I see omens in every event and action. The gods try to speak to us, we just need to listen.",
   :background_id => 1
  },
  {:description => "Nothing can shake my optimistic attitude.",
   :background_id => 1
  },
  {:description => "I quote (or misquote) sacred texts and proverbs in almost every situation.",
   :background_id => 1
  },
  {:description => "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.",
   :background_id => 1
  },
  {:description => "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
   :background_id => 1
  },
  {:description => "I've spent so long in the temple that I have little practical experience in dealing with people in the outside world.",
   :background_id => 1
  }
])
Ideal.create([
  {:name => "Tradition",
   :description => "The ancient traditions of worship and sacrifice must be preserved and upheld.",
   :alignment => ['Lawful'],
   :background_id => 1
  },
  {:name => "Charity",
   :description => "I always try to help those in need, no matter what the personal cost.",
   :alignment => ['Good'],
   :background_id => 1
  },
  {:name => "Change",
   :description => "We must help bring about the changes the gods are constantly working in the world",
   :alignment => ['Chaotic'],
   :background_id => 1
  },
  {:name => "Power",
   :description => "I hope to one day rise to the top of my faith's religious hierarchy.",
   :alignment => ['Lawful'],
   :background_id => 1
  },
  {:name => "Faith",
   :description => "I trust that my deity will guide my actions. I have faith that if I work hard, things will go well.",
   :alignment => ['Lawful'],
   :background_id => 1
  },
  {:name => "Aspiration",
   :description => "I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings.",
   :alignment => [],
   :background_id => 1
  }
])
Bond.create([
  {:description => "I would die to recover an ancient relic of my faith that was lost long ago.",
   :background_id => 1
  },
  {:description => "I will someday get revenge on the corrupt temple of hierarchy who branded me a heretic.",
   :background_id => 1
  },
  {:description => "I owe my life to the priest who took me in when my parents died.",
   :background_id => 1
  },
  {:description => "Everything I do if for the common people.",
   :background_id => 1
  },
  {:description => "I will do anything to protect the temple where I served.",
   :background_id => 1
  },
  {:description => "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
   :background_id => 1
  },
])
Flaw.create([
  {:description => "I judge others harshly, and myself even more severely.",
   :background_id => 1
  },
  {:description => "I put too much trust in those who wield power with my temple's hierarchy.",
   :background_id => 1
  },
  {:description => "My piety sometimes leads me to blindly trust those that profess faith in my god.",
   :background_id => 1
  },
  {:description => "I am inflexible in my thinking.",
   :background_id => 1
  },
  {:description => "I am suspicious of strangers and expect the worst of them.",
   :background_id => 1
  },
  {:description => "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
   :background_id => 1
  }
])
BackgroundExtra.create([
  {:name => "Suggested Characteristics",
   :description => "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.",
   :values => {},
   :background_id => 1
  }
])
EquipmentType.create([
  {:name => 'Light Armor',
   :description => 'Made from supple and thin materials, light armor favors agile adventurers since it offers some protection without sacrificing mobility. If you wear light armor, you add your Dexterity modifier to the base number from your armor type to determine your Armor Class.'
  },
  {:name => 'Simple Weapons',
   :description => 'Weapons which require little to no training to use correctly and effectively.'
  },
  {:name => 'Adventuring Gear',
   :description => 'Gear a traveling adventure might carry on their persons.'
  }
])
Armor.create([
  {:name => 'Padded Armor',
   :equipment_type_id => 1,
   :cost => 5,
   :currency => 'GP',
   :description => 'Padded armor consists of quilted layers of cloth and batting.',
   :image => 'padded_armor.jpg',
   :AC => 11,
   :AC_modifier => 'Dex',
   :AC_modifier_max => 10,
   :strength => 0,
   :stealth_disadvantage => true,
   :weight => 8
  }
])
WeaponProperty.create([
  {:name => 'Light',
   :description => 'Small and easy to handle, making it ideal for use when fighting with two weapons.'
  }
])
Weapon.create([
  {:name => 'Club',
   :equipment_type_id => 2,
   :cost => 1,
   :currency => 'SP',
   :damage => '1d4',
   :damage_type => 'Bludgeoning',
   :weight => 2,
   :properties => [1],
   :image => 'club.jpg',
   :range => "",
   :versatile => "",
   :weapon_special_id => ''
  }
])
Gear.create([
  {:name => 'Abacus',
   :cost => 2,
   :currency => 'GP',
   :weight => 2,
   :equipment_type_id => 3,
   :image => 'abacus.jpg',
   :description => 'An oblong frame with rows of wires or grooves along which beads are slid, used for calculating.'
  }
])
Tool.create([
  {:name => "Alchemist's Tools",
   :description => 'Tools required for basic alchemical acts',
   :cost => 50,
   :currency => 'GP',
   :weight => 8,
  }
])
CharClass.create([
  {:name => 'Barbarian',
   :description => 'A fierce warrior of primitive background who can enter a battle rage',
   :image => 'barbarian.png',
   :primary_ability => 'Str',
   :bio => "A tall human tribesman strides through a blizzard, draped in fur and hefting his axe. He laughs as he charges toward the frost giant who dared poach his people's elk herd. A half-orc snarls at the latest challenger to her authority over their savage tribe, ready to break his neck with her bare hands as she did to the last six rivals. Frothing at the mouth, a dwarf slams his helmet into the face of his drow foe, then turns to drive his armored elbow into the gut of another. These barbarians, different as they might be, are defined by their rage: unbridled, unquenchable, and unthinking fury. More than a mere emotion, their anger is the ferocity of a cornered predator, the unrelenting",
   :saving_throws => ['Str', 'Con'],
   :hit_dice => '1d12',
   :hp_at_first_level => 12,
   :hp_at_first_level_attribute => 'Con',
   :hp_at_higher_levels => '1d12',
   :hp_at_higher_levels_min => 7,
   :hp_at_higher_levels_attribute => 'Con',
   :starting_equipment => {items: [
     {quantity: 1, choices: ['Greataxe', 'Any Martial Weapon']},
     {quantity: [2,1], choices: ['Handaxe', 'Any Simple Weapon']},
     {quantity: 1, choices: ["Explorer's Pack"]},
     {quantity: 4, choices: ["Javelin"]},
   ]},
   :armor_prof => ['Light Armor', 'Medium Armor', 'Shield'],
   :weapon_prof => ['Simple Weapon', 'Martial Weapon'],
   :skill_prof => 2,
   :tool_prof => [],
   :skill_prof_choices => [2, 4, 8, 11, 12, 18],
   :fund_modifier => 10,
   :fund_roll => '2d4'
  }
])
ClassPath.create([
  {:name => 'Path of the Berserker',
   :description => "For some barbarians, rage is a means to an end - that end being violence. The Path of the Berserker is a path of untrammeled fury, slick with blood. As you enter the berserker's rage. you thrill in the chaos of battle, heedless of your own health or well-being.",
   :feats => [2,3,4,5],
   :char_class_id => 1
  }
])
ClassLevel.create([
  {:level => 1,
   :prof_bonus => 2,
   :features => [6, 7],
   :info => {rages: 2, rage_damage: '+2'},
   :char_class_id => 1
  }
])
Component.create([
  {:name => 'Verbal',
   :description => "Most spells require the chanting of mystic words. The words themselves aren't the source of the spell's power; rather, the particular combination of sounds, with specific pitch and resonance, sets the threads of magic in motion. Thus, a character who is gagged or in an area of silence, such as one created by the silence spell, can't cast a spell with a verbal component."
  },
  {:name => 'Somatic',
   :description => "Spellcasting gestures might include a forceful gesticulation or an intricate set of gestures. If a spell requires a somatic component, the caster must have free use of at least one hand to perform these gestures."
  },
  {:name => 'Material',
   :description => "Casting some spells requires particular objects, specified in parentheses in the component entry. A character can use a component pouch or a speIlcasting focus (found in chapter 5) in place of the components specified for a spell. But if a cost is indicated for a component, a character must have that specific component before he or she can cast the spell. If a spell states that a material component is consumed by the spell, the caster must provide this component for each casting of the spell. A spellcaster must have a hand free to access these components, but it can be the same hand that he or she uses to perform somatic components."
  }
])
Spell.create([
  {:name => 'Acid Splash',
   :level => 2,
   :spell_type => 'Abjuration',
   :casting_time => 1,
   :time_unit => 'action',
   :components => [1,2],
   :duration => 'Instantaneous',
   :description => "You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or lake 1d6 acid damage. This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
   :range => 60,
   :range_unit => 'feet',
   :table => {},
   :materials => {}
 }
])
